# Travis doesn't have a fortran build config, so we'll use c as a base and
# create our own environment
language: c
compiler: gcc
env:
    global:
        - FC=gfortran-4.8
        - OMPI_FC=${FC}
install:
    - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install gfortran-4.8 libgomp1
    - sudo apt-get install openmpi-bin libopenmpi-dev
    - git clone --depth 50 --branch pfunit_2.1.0 git://git.code.sf.net/p/pfunit/code pfunit-code
    - make -C pfunit-code MPI=yes OPENMP=yes
    - make install -C pfunit-code INSTALL_DIR=../pfunit
script: make check PFUNIT=pfunit
